export interface EAConfig {
  emaFastPeriod: number;
  emaSlowPeriod: number;
  rsiPeriod: number;
  rsiOverbought: number;
  rsiOversold: number;
  bbPeriod: number;
  bbDeviation: number;
  atrPeriod: number;
  atrSlMultiplier: number;
  atrTpMultiplier: number;
  minSignalScore: number;
  riskPerTrade: number;
  maxDailyLoss: number;
  maxDrawdown: number;
}

// ---------------------------------------------------------------------------
// GoldScalperPro MQL4 generator — v3.0
//
// AUDIT NOTE (see audit/AUDIT_REPORT.md): the v2.0 generator below produced an
// EA that only voted on EMA/RSI/Bollinger Bands across M1/M5/M15 — none of the
// seven advertised engines (SMC, Wyckoff, Price Action, Trend Gate, Entry
// Filter, Quality Filter, Capital Manager) were present in the code that
// actually runs on a live account. v3.0 ports the SAME decision pipeline used
// by analyzeSmcStructure() (smcEngine.ts) — the function the live
// /gold/signals and /gold/smc routes call — into MQL4, operating on the M5
// timeframe (the only timeframe the SMC/Wyckoff/PA engines are tuned for; M1
// config exists too but the live dashboard's primary signal is M5, matching
// the backtest engine fix). No new indicators or thresholds were invented —
// every constant below is copied from the corresponding .ts engine file.
//
// cfg.emaFastPeriod / emaSlowPeriod / rsiPeriod / rsiOverbought / rsiOversold /
// bbPeriod / bbDeviation / atrSlMultiplier / atrTpMultiplier / minSignalScore
// belonged to the OLD 3-timeframe voting system, which is removed. They are
// kept in EAConfig/DB for backward compatibility but are UNUSED by v3.0 — SL/
// TP now come from Capital Manager (structural, not flat ATR-multiple) and
// signal quality comes from Entry Filter + Quality Filter, not a single score
// threshold. cfg.riskPerTrade, maxDailyLoss, maxDrawdown, and atrPeriod are
// still used (risk guard + Capital Manager ATR).
// ---------------------------------------------------------------------------

export function generateEACode(cfg: EAConfig): string {
  return `//+------------------------------------------------------------------+
//|  GoldScalperPro - XAU/USD Scalper (SMC+Wyckoff+PA pipeline)       |
//|  Generated by Gold Scalper Bot Dashboard                          |
//|  Version: 4.0 | Timeframe: M5 | Confidence Score Decision Engine |
//|                                                                    |
//|  v4.0 replaces the old 3-of-4 vote system with a professional     |
//|  0–100% Confidence Engine. No trade opens below 85%; normal floor |
//|  is 90%+ (regime-adaptive). Market Regime Detector adds per-regime|
//|  thresholds. Decision Logger prints full score breakdown per bar.  |
//|  Ports decisionEngine + confidenceEngine + marketRegimeDetector.  |
//+------------------------------------------------------------------+
#property copyright "Gold Scalper Pro"
#property link      ""
#property version   "4.00"
#property strict

//--- Legacy inputs (kept for DB/UI compatibility — UNUSED by v3.0 pipeline,
//    see audit/AUDIT_REPORT.md). SL/TP/entry quality are now decided by the
//    SMC+Wyckoff+PA+Trend+EntryFilter+QualityFilter+CapitalManager pipeline.
input int    EMA_Fast_Period_LEGACY = ${cfg.emaFastPeriod};
input int    EMA_Slow_Period_LEGACY = ${cfg.emaSlowPeriod};
input int    RSI_Period_LEGACY      = ${cfg.rsiPeriod};
input double RSI_Overbought_LEGACY  = ${cfg.rsiOverbought};
input double RSI_Oversold_LEGACY    = ${cfg.rsiOversold};
input int    BB_Period_LEGACY       = ${cfg.bbPeriod};
input double BB_Deviation_LEGACY    = ${cfg.bbDeviation};
input double ATR_SL_Mult_LEGACY     = ${cfg.atrSlMultiplier};
input double ATR_TP_Mult_LEGACY     = ${cfg.atrTpMultiplier};
input double Min_Signal_Score_LEGACY= ${cfg.minSignalScore};

//--- Active inputs (used by v4.0 pipeline)
input int    ATR_Period        = ${cfg.atrPeriod};         // ATR period (Capital Manager)
input double Risk_Per_Trade    = ${cfg.riskPerTrade};       // Risk Per Trade (%)
input double Max_Daily_Loss    = ${cfg.maxDailyLoss};       // Max Daily Loss (%)
input double Max_Drawdown      = ${cfg.maxDrawdown};        // Max Drawdown (%)
input int    Magic_Number      = 20250704;
input string EA_Comment        = "GoldScalperPro";

//===================================================================
// SMC / WYCKOFF / PRICE ACTION CONFIG — copied verbatim from CFG_M5
// in smcEngine.ts / wyckoffEngine.ts / priceActionEngine.ts.
//===================================================================
#define BARS_NEEDED           250   // enough for EMA200 + all lookbacks

// smcEngine.ts CFG_M5
#define SMC_SWING_LOOKBACK        5
#define SMC_FVG_MIN_SIZE          0.10
#define SMC_LIQ_SWEEP_MIN         0.15
#define SMC_MIN_SWEEP_CLOSE_MARGIN 0.10
#define SMC_NEAR_OB_THRESHOLD     0.50
#define SMC_NEAR_FVG_THRESHOLD    0.30
#define SMC_MIN_OB_BODY_SIZE      0.15
#define SMC_MIN_OB_BODY_RATIO     0.30
#define SMC_MIN_BREAK_DISTANCE    0.20
#define SMC_MIN_BOS_BODY_RATIO    0.35
#define SMC_MAX_OB                6
#define SMC_MAX_FVG               6
#define SMC_MAX_BOS               5
#define SMC_MAX_CHOCH             3
#define SMC_MAX_SWEEP             5

// wyckoffEngine.ts CFG_M5
#define WY_RANGE_BARS             20
#define WY_TREND_BARS             12
#define WY_SPRING_MARGIN          0.20
#define WY_UPTHRUST_MARGIN        0.20
#define WY_MIN_RANGE_TOUCHES      2
#define WY_MAX_RANGE_PCT          0.010
#define WY_MIN_RANGE_PCT          0.001
#define WY_RECENT_BARS            6

// priceActionEngine.ts CFG_M5
#define PA_PINBAR_WICK_RATIO      2.0
#define PA_PINBAR_BODY_MAX_RATIO  0.30
#define PA_STRONG_BODY_RATIO      0.60
#define PA_STRONG_BODY_ATR_MULT   0.40
#define PA_ENGULF_BODY_RATIO      1.05
#define PA_LEVEL_LOOKBACK         30
#define PA_LEVEL_TOLERANCE        0.35
#define PA_MIN_LEVEL_TOUCHES      2
#define PA_BREAKOUT_MIN_BODY      0.20
#define PA_BREAKOUT_BODY_RATIO    0.50
#define PA_FAKE_RETRACE_BARS      3
#define PA_PULLBACK_ZONE_PCT      0.0015
#define PA_ATR_PERIOD             10

// qualityFilter.ts (legacy identifiers — kept for reference only)
#define QF_LATE_EXTENSION_MULT    2.0
#define QF_MOMENTUM_BARS          5
#define QF_STALE_BAR_COUNT        8

// Confidence Engine (v4.0) — decisionEngine.ts / confidenceEngine.ts
#define CONF_HARD_MIN         85.0   // trades below 85% always rejected
#define CONF_MARGINAL_MIN_RR  2.0    // 85%–threshold zone: only pass if R:R >= 2.0
#define CONF_ADX_MIN          15.0   // ADX < 15 = no momentum, block
#define CONF_ATR_HIGH_VOL     1.8    // ATR ratio above this = HIGH_VOLATILITY
#define CONF_ATR_LOW_VOL      0.60   // ATR ratio below (ADX<20) = LOW_VOLATILITY
#define CONF_ADX_STRONG       30.0   // ADX >= 30 + STRONG EMAs = STRONG_TREND

// capitalManager.ts
#define CM_ATR_BUFFER_MULT        0.25
#define CM_MIN_SL_ATR_MULT        0.50
#define CM_MAX_SL_ATR_MULT        3.00
#define CM_MIN_REWARD_RISK        1.50
#define CM_MAX_TP_ATR_MULT        5.00
#define CM_TRAIL_ATR_MULT         0.70
#define CM_TRAIL_ACTIVATION       1.00
#define CM_BE_ACTIVATION          1.00
#define CM_BE_BUFFER_MULT         0.10
#define CM_LOT_DOLLAR_PER_UNIT    100.0
#define CM_MIN_LOT                0.01
#define CM_MAX_LOT                50.0

//===================================================================
// GLOBALS — chronological candle buffers (index 0 = oldest, N-1 = newest
// CLOSED bar). MQL4 series arrays are reverse-chronological (0 = current
// forming bar), so FillCandles() copies+reverses into these buffers,
// deliberately skipping the still-forming bar (shift 0) to avoid repainting —
// exactly like goldEngine.ts candles, which are always fully-closed bars.
//===================================================================
double g_o[BARS_NEEDED], g_h[BARS_NEEDED], g_l[BARS_NEEDED], g_c[BARS_NEEDED], g_v[BARS_NEEDED];
datetime g_t[BARS_NEEDED];
int g_n = 0;

double g_DailyStartBalance = 0;
datetime g_DayStart = 0;

struct SBos    { string dir; double price; int barIndex; };
struct SChoch  { string dir; double price; int barIndex; };
struct SOb     { string typ; double high; double low; int barIndex; bool mitigated; };
struct SFvg    { string typ; double top; double bottom; };
struct SSweep  { string dir; double level; };

SBos   g_bos[SMC_MAX_BOS];    int g_bosCount = 0;
SChoch g_choch[SMC_MAX_CHOCH]; int g_chochCount = 0;
SOb    g_ob[SMC_MAX_OB];      int g_obCount = 0;
SFvg   g_fvg[SMC_MAX_FVG];    int g_fvgCount = 0;
SSweep g_sweep[SMC_MAX_SWEEP]; int g_sweepCount = 0;
string g_finalTrend = "NEUTRAL"; // BULLISH | BEARISH | NEUTRAL

// Decision Engine adaptive state (set by DetectMarketRegime each bar)
string g_regime     = "RANGE";   // current market regime
double g_minConf    = 90.0;      // regime-specific minimum confidence
double g_minRR      = 1.5;       // regime-specific minimum R:R
bool   g_allowLong  = true;      // regime allows BUY entries
bool   g_allowShort = true;      // regime allows SELL entries

//+------------------------------------------------------------------+
int OnInit() {
   g_DailyStartBalance = AccountBalance();
   Print("GoldScalperPro v4.0 initialized (Confidence Score Decision Engine). Balance: ", AccountBalance());
   return(INIT_SUCCEEDED);
}
void OnDeinit(const int reason) { Print("GoldScalperPro stopped. Reason: ", reason); }

//+------------------------------------------------------------------+
//| Core loop — v4.0 Confidence Score Decision Engine                 |
//+------------------------------------------------------------------+
void OnTick() {
   if(g_DayStart == 0 || TimeDay(TimeCurrent()) != TimeDay(g_DayStart)) {
      g_DayStart = TimeCurrent();
      g_DailyStartBalance = AccountBalance();
   }

   if(!IsRiskAllowed()) return;
   if(!IsNewBar()) return;

   if(CountOpenTrades() > 0) {
      ManageOpenTrades();
      return;
   }

   FillCandles();
   if(g_n < SMC_SWING_LOOKBACK * 2 + 10) return;

   // ── Detection pipeline (unchanged from v3.0) ─────────────────────
   DetectSwingsAndStructure();
   DetectOrderBlocks();
   DetectFvgs();
   DetectSweeps();

   // ── Engine outputs ────────────────────────────────────────────────
   double wyScore; string wySignal; bool wySpring, wyUpthrust, wyVolConf;
   AnalyzeWyckoff(wySignal, wyScore, wySpring, wyUpthrust, wyVolConf);

   string paSignal; double paScore;
   bool paBullEngulf, paBearEngulf, paBullPin, paBearPin, paStrongBull, paStrongBear;
   bool paNearDemand, paNearSupply, paNearSupport, paNearResistance;
   bool paValidBullBO, paValidBearBO, paFakeBullBO, paFakeBearBO;
   double paSupportLevel, paResistanceLevel;
   AnalyzePriceAction(paSignal, paScore, paBullEngulf, paBearEngulf, paBullPin, paBearPin,
                      paStrongBull, paStrongBear, paNearDemand, paNearSupply, paNearSupport,
                      paNearResistance, paValidBullBO, paValidBearBO, paFakeBullBO, paFakeBearBO,
                      paSupportLevel, paResistanceLevel);

   string emaTrend, emaStrength;
   AnalyzeTrend(emaTrend, emaStrength);

   // ── Candidate direction (CHoCH > BOS > finalTrend) ───────────────
   string candidate = CalcSmcCandidateDir();
   if(candidate == "NEUTRAL") return;

   // ── Hard EMA gate — direct opposition always blocks ───────────────
   if((candidate == "BUY"  && emaTrend == "BEARISH") ||
      (candidate == "SELL" && emaTrend == "BULLISH")) return;

   // ── Market Regime Detector ────────────────────────────────────────
   double atr     = iATR(Symbol(), PERIOD_M5, ATR_Period, 1);
   double adx     = iADX(Symbol(), PERIOD_M5, 14, PRICE_CLOSE, MODE_MAIN, 1);
   double atrMean = CalcAtrMean(20);
   DetectMarketRegime(atr, atrMean, adx, emaTrend, emaStrength, wySignal);

   // ── Session quality (UTC, matches qualityFilter.ts windows) ───────
   int utcHour = TimeHour(TimeGMT());
   string sessionQuality = "BLOCKED";
   if(utcHour >= 0  && utcHour < 3)  sessionQuality = "MODERATE";
   if(utcHour >= 6  && utcHour < 12) sessionQuality = "PRIME";
   if(utcHour >= 12 && utcHour < 16) sessionQuality = "PRIME";
   if(utcHour >= 16 && utcHour < 17) sessionQuality = "MODERATE";

   // ── Confidence Score Engine ───────────────────────────────────────
   double atrRatio = (atrMean > 0) ? atr / atrMean : 1.0;
   bool hasSweep = (g_sweepCount > 0 &&
                    g_sweep[g_sweepCount-1].dir == (candidate == "BUY" ? "BULLISH" : "BEARISH"));
   // Equal-level approximation: 2+ BOS in same direction at close prices
   bool hasEqLvl = false;
   if(g_bosCount >= 2) {
      int sameDirCnt = 0;
      for(int b = 0; b < g_bosCount; b++) if(g_bos[b].dir == candidate) sameDirCnt++;
      hasEqLvl = (sameDirCnt >= 2);
   }

   double smcPts, trendPts, paPts, wykPts, liqPts, volPts;
   double confidence = CalcConfidenceScore(
      candidate,
      wySignal, wyScore, wySpring, wyUpthrust, wyVolConf,
      paSignal, paScore, paBullEngulf, paBearEngulf, paBullPin, paBearPin,
      paStrongBull, paStrongBear, paFakeBullBO, paFakeBearBO, paValidBullBO, paValidBearBO,
      emaTrend, emaStrength,
      sessionQuality, atrRatio, adx, hasSweep, hasEqLvl,
      smcPts, trendPts, paPts, wykPts, liqPts, volPts
   );

   // Quick pre-check: avoid CalcTradeParameters call if obviously rejected
   if(confidence < CONF_HARD_MIN) {
      Print(">>> SKIP: ", candidate, " | Confidence: ", DoubleToString(confidence, 1), "% < 85% hard minimum");
      return;
   }

   // ── Capital Manager: SL/TP/lots (needed for R:R before quality gate) ─
   if(atr <= 0) return;
   double obTop = 0, obBottom = 0; bool haveOb = false;
   for(int i = g_obCount - 1; i >= 0; i--) {
      if(candidate == "BUY"  && g_ob[i].typ == "BULLISH") { obTop = g_ob[i].high; obBottom = g_ob[i].low; haveOb = true; break; }
      if(candidate == "SELL" && g_ob[i].typ == "BEARISH") { obTop = g_ob[i].high; obBottom = g_ob[i].low; haveOb = true; break; }
   }
   double swingHigh = NearestSwingHigh();
   double swingLow  = NearestSwingLow();

   double entry = (candidate == "BUY") ? Ask : Bid;
   double sl, tp, trailDist, trailActivateAt, beAt, beSL, lots, riskAmt;
   CalcTradeParameters(candidate, entry, atr, haveOb, obTop, obBottom, swingHigh, swingLow,
                        paResistanceLevel, paSupportLevel,
                        sl, tp, trailDist, trailActivateAt, beAt, beSL, lots, riskAmt);

   double slDist  = MathAbs(entry - sl);
   double tpDist  = MathAbs(entry - tp);
   double rrRatio = (slDist > 0) ? NormalizeDouble(tpDist / slDist, 2) : 0;

   // ── Enhanced Quality Filter (10-category gate) ────────────────────
   string blockReason = "";
   bool allowed = EnhancedQualityFilter(candidate, confidence, rrRatio,
                                         sessionQuality, adx, blockReason);

   // ── Decision Logger ───────────────────────────────────────────────
   LogDecision(candidate, confidence, g_regime,
               smcPts, trendPts, paPts, wykPts, liqPts, volPts,
               rrRatio, allowed, blockReason);

   if(!allowed || lots <= 0) return;

   OpenTrade(candidate == "BUY" ? OP_BUY : OP_SELL, lots, entry, sl, tp);
}

//===================================================================
// CANDLE BUFFER
//===================================================================
void FillCandles() {
   g_n = 0;
   int avail = MathMin(BARS_NEEDED, iBars(Symbol(), PERIOD_M5) - 1);
   for(int shift = avail; shift >= 1; shift--) {
      g_o[g_n] = iOpen(Symbol(), PERIOD_M5, shift);
      g_h[g_n] = iHigh(Symbol(), PERIOD_M5, shift);
      g_l[g_n] = iLow(Symbol(), PERIOD_M5, shift);
      g_c[g_n] = iClose(Symbol(), PERIOD_M5, shift);
      g_v[g_n] = (double)iVolume(Symbol(), PERIOD_M5, shift);
      g_t[g_n] = iTime(Symbol(), PERIOD_M5, shift);
      g_n++;
   }
}

double Body(int i)  { return MathAbs(g_c[i] - g_o[i]); }
double Rng(int i)   { return g_h[i] - g_l[i]; }
double BodyRatio(int i) { double r = Rng(i); return r > 0 ? Body(i) / r : 0; }
bool   IsBull(int i) { return g_c[i] > g_o[i]; }
bool   IsBear(int i) { return g_c[i] < g_o[i]; }
double UpperWick(int i) { return g_h[i] - MathMax(g_o[i], g_c[i]); }
double LowerWick(int i) { return MathMin(g_o[i], g_c[i]) - g_l[i]; }

//===================================================================
// SWING / BOS / CHoCH — ports detectSwingHighs/Lows + detectBosAndChoch
// (smcEngine.ts). Fake-BOS filter: break distance + body-ratio gates.
//===================================================================
int g_swHigh[BARS_NEEDED]; int g_swHighCount = 0;
int g_swLow[BARS_NEEDED];  int g_swLowCount  = 0;

void DetectSwings() {
   g_swHighCount = 0; g_swLowCount = 0;
   int lb = SMC_SWING_LOOKBACK;
   for(int i = lb; i < g_n - lb; i++) {
      bool validHigh = true, validLow = true;
      for(int j = 1; j <= lb; j++) {
         if(g_h[i - j] >= g_h[i] || g_h[i + j] >= g_h[i]) validHigh = false;
         if(g_l[i - j] <= g_l[i] || g_l[i + j] <= g_l[i]) validLow = false;
      }
      if(validHigh && g_swHighCount < BARS_NEEDED) g_swHigh[g_swHighCount++] = i;
      if(validLow  && g_swLowCount  < BARS_NEEDED) g_swLow[g_swLowCount++]  = i;
   }
}

double NearestSwingHigh() {
   double price = g_c[g_n - 1];
   double best = 0;
   for(int i = g_swHighCount - 1; i >= 0; i--) {
      if(g_h[g_swHigh[i]] > price) { best = g_h[g_swHigh[i]]; break; }
   }
   return best;
}
double NearestSwingLow() {
   double price = g_c[g_n - 1];
   double best = 0;
   for(int i = g_swLowCount - 1; i >= 0; i--) {
      if(g_l[g_swLow[i]] < price) { best = g_l[g_swLow[i]]; break; }
   }
   return best;
}

void DetectSwingsAndStructure() {
   DetectSwings();
   g_bosCount = 0; g_chochCount = 0;
   bool usedHigh[BARS_NEEDED]; bool usedLow[BARS_NEEDED];
   ArrayInitialize(usedHigh, 0); ArrayInitialize(usedLow, 0);

   string localTrend = "NEUTRAL";
   string recentBos1 = "", recentBos2 = ""; // last two BOS directions

   double chochBodyRatio = SMC_MIN_BOS_BODY_RATIO * 0.8;

   for(int i = SMC_SWING_LOOKBACK; i < g_n; i++) {
      double br = BodyRatio(i);

      int recentShPos = -1;
      for(int k = g_swHighCount - 1; k >= 0; k--) {
         if(g_swHigh[k] < i && !usedHigh[k]) { recentShPos = k; break; }
      }
      int recentSlPos = -1;
      for(int k = g_swLowCount - 1; k >= 0; k--) {
         if(g_swLow[k] < i && !usedLow[k]) { recentSlPos = k; break; }
      }

      if(recentShPos >= 0) {
         double shPrice = g_h[g_swHigh[recentShPos]];
         double breakDist = g_c[i] - shPrice;
         double minBody = (localTrend == "BEARISH") ? chochBodyRatio : SMC_MIN_BOS_BODY_RATIO;
         if(breakDist >= SMC_MIN_BREAK_DISTANCE && br >= minBody) {
            if(localTrend == "BEARISH") {
               if(g_chochCount < SMC_MAX_CHOCH) { g_choch[g_chochCount].dir = "BUY"; g_choch[g_chochCount].price = shPrice; g_choch[g_chochCount].barIndex = i; g_chochCount++; }
               localTrend = "NEUTRAL"; recentBos1 = ""; recentBos2 = "";
            } else {
               if(g_bosCount < SMC_MAX_BOS) { g_bos[g_bosCount].dir = "BUY"; g_bos[g_bosCount].price = shPrice; g_bos[g_bosCount].barIndex = i; g_bosCount++; }
               recentBos1 = recentBos2; recentBos2 = "BUY";
               if(recentBos1 == "BUY" && recentBos2 == "BUY") localTrend = "BULLISH";
            }
            usedHigh[recentShPos] = true;
         }
      }

      if(recentSlPos >= 0) {
         double slPrice = g_l[g_swLow[recentSlPos]];
         double breakDist2 = slPrice - g_c[i];
         double minBody2 = (localTrend == "BULLISH") ? chochBodyRatio : SMC_MIN_BOS_BODY_RATIO;
         if(breakDist2 >= SMC_MIN_BREAK_DISTANCE && br >= minBody2) {
            if(localTrend == "BULLISH") {
               if(g_chochCount < SMC_MAX_CHOCH) { g_choch[g_chochCount].dir = "SELL"; g_choch[g_chochCount].price = slPrice; g_choch[g_chochCount].barIndex = i; g_chochCount++; }
               localTrend = "NEUTRAL"; recentBos1 = ""; recentBos2 = "";
            } else {
               if(g_bosCount < SMC_MAX_BOS) { g_bos[g_bosCount].dir = "SELL"; g_bos[g_bosCount].price = slPrice; g_bos[g_bosCount].barIndex = i; g_bosCount++; }
               recentBos1 = recentBos2; recentBos2 = "SELL";
               if(recentBos1 == "SELL" && recentBos2 == "SELL") localTrend = "BEARISH";
            }
            usedLow[recentSlPos] = true;
         }
      }
   }
   g_finalTrend = localTrend;
}

//===================================================================
// ORDER BLOCKS — ports detectOrderBlocks (smcEngine.ts), weak-OB filter
// (body size + body ratio) and mitigation check.
// usedObBar guards against two BOS events claiming the same OB candle,
// matching the usedObIdx Set<number> in the TypeScript source.
//===================================================================
void DetectOrderBlocks() {
   g_obCount = 0;
   bool usedObBar[BARS_NEEDED]; ArrayInitialize(usedObBar, 0);
   for(int b = 0; b < g_bosCount; b++) {
      int barIndex = g_bos[b].barIndex;
      int maxLook = MathMin(8, barIndex);
      int obIdx = -1;
      if(g_bos[b].dir == "BUY") {
         for(int k = barIndex - 1; k >= barIndex - maxLook; k--) {
            if(k < 0) break;
            if(!usedObBar[k] && IsBear(k) && Body(k) >= SMC_MIN_OB_BODY_SIZE && BodyRatio(k) >= SMC_MIN_OB_BODY_RATIO) { obIdx = k; break; }
         }
      } else {
         for(int k = barIndex - 1; k >= barIndex - maxLook; k--) {
            if(k < 0) break;
            if(!usedObBar[k] && IsBull(k) && Body(k) >= SMC_MIN_OB_BODY_SIZE && BodyRatio(k) >= SMC_MIN_OB_BODY_RATIO) { obIdx = k; break; }
         }
      }
      if(obIdx < 0) continue;

      bool mitigated = false;
      for(int j = barIndex + 1; j < g_n; j++) {
         if(g_l[j] <= g_h[obIdx] && g_h[j] >= g_l[obIdx]) { mitigated = true; break; }
      }
      if(mitigated) continue; // only ACTIVE (unmitigated) OBs are kept, matching smcEngine.ts

      if(g_obCount < SMC_MAX_OB) {
         g_ob[g_obCount].typ = (g_bos[b].dir == "BUY") ? "BULLISH" : "BEARISH";
         g_ob[g_obCount].high = g_h[obIdx];
         g_ob[g_obCount].low  = g_l[obIdx];
         g_ob[g_obCount].barIndex = obIdx;
         g_ob[g_obCount].mitigated = false;
         g_obCount++;
         usedObBar[obIdx] = true; // prevent two BOS events from claiming the same OB candle
      }
   }
}

//===================================================================
// FAIR VALUE GAPS — ports detectFairValueGaps (smcEngine.ts)
//===================================================================
void DetectFvgs() {
   g_fvgCount = 0;
   double currentHigh = g_h[g_n - 1], currentLow = g_l[g_n - 1];
   for(int i = 2; i < g_n; i++) {
      int c1 = i - 2, c3 = i;
      if(g_h[c1] < g_l[c3] && (g_l[c3] - g_h[c1]) >= SMC_FVG_MIN_SIZE) {
         bool filled = false;
         for(int j = i + 1; j < g_n; j++) if(g_l[j] <= g_l[c3] && g_h[j] >= g_h[c1]) { filled = true; break; }
         if(!filled && currentLow <= g_l[c3] && currentHigh >= g_h[c1]) filled = true;
         if(!filled && g_fvgCount < SMC_MAX_FVG) { g_fvg[g_fvgCount].typ = "BULLISH"; g_fvg[g_fvgCount].top = g_l[c3]; g_fvg[g_fvgCount].bottom = g_h[c1]; g_fvgCount++; }
      }
      if(g_l[c1] > g_h[c3] && (g_l[c1] - g_h[c3]) >= SMC_FVG_MIN_SIZE) {
         bool filled = false;
         for(int j = i + 1; j < g_n; j++) if(g_h[j] >= g_h[c3] && g_l[j] <= g_l[c1]) { filled = true; break; }
         if(!filled && currentHigh >= g_h[c3] && currentLow <= g_l[c1]) filled = true;
         if(!filled && g_fvgCount < SMC_MAX_FVG) { g_fvg[g_fvgCount].typ = "BEARISH"; g_fvg[g_fvgCount].top = g_l[c1]; g_fvg[g_fvgCount].bottom = g_h[c3]; g_fvgCount++; }
      }
   }
}

//===================================================================
// LIQUIDITY SWEEPS — ports detectLiquiditySweeps (smcEngine.ts)
//===================================================================
void DetectSweeps() {
   g_sweepCount = 0;
   for(int i = SMC_SWING_LOOKBACK; i < g_n; i++) {
      for(int k = g_swLowCount - 1; k >= 0; k--) {
         int idx = g_swLow[k];
         if(idx >= i || idx < i - 20) continue;
         double level = g_l[idx];
         bool wickOk = (level - g_l[i]) >= SMC_LIQ_SWEEP_MIN;
         bool closeOk = (g_c[i] - level) >= SMC_MIN_SWEEP_CLOSE_MARGIN;
         bool bodyOk = IsBull(i);
         if(wickOk && closeOk && bodyOk) {
            bool dup = false;
            for(int s = 0; s < g_sweepCount; s++) if(g_sweep[s].dir == "BULLISH" && MathAbs(g_sweep[s].level - level) < 0.05) dup = true;
            if(!dup && g_sweepCount < SMC_MAX_SWEEP) { g_sweep[g_sweepCount].dir = "BULLISH"; g_sweep[g_sweepCount].level = level; g_sweepCount++; }
            break;
         }
      }
      for(int k = g_swHighCount - 1; k >= 0; k--) {
         int idx = g_swHigh[k];
         if(idx >= i || idx < i - 20) continue;
         double level = g_h[idx];
         bool wickOk = (g_h[i] - level) >= SMC_LIQ_SWEEP_MIN;
         bool closeOk = (level - g_c[i]) >= SMC_MIN_SWEEP_CLOSE_MARGIN;
         bool bodyOk = IsBear(i);
         if(wickOk && closeOk && bodyOk) {
            bool dup = false;
            for(int s = 0; s < g_sweepCount; s++) if(g_sweep[s].dir == "BEARISH" && MathAbs(g_sweep[s].level - level) < 0.05) dup = true;
            if(!dup && g_sweepCount < SMC_MAX_SWEEP) { g_sweep[g_sweepCount].dir = "BEARISH"; g_sweep[g_sweepCount].level = level; g_sweepCount++; }
            break;
         }
      }
   }
}

//===================================================================
// WYCKOFF — ports wyckoffEngine.ts analyzeWyckoff (CFG_M5)
//===================================================================
void AnalyzeWyckoff(string &signal, double &score, bool &spring, bool &upthrust, bool &volumeConfirmed) {
   signal = "NEUTRAL"; score = 0; spring = false; upthrust = false; volumeConfirmed = false;
   if(g_n < WY_RANGE_BARS + WY_TREND_BARS) return;

   int rangeStart = g_n - WY_RANGE_BARS;
   double support = g_l[rangeStart], resistance = g_h[rangeStart];
   for(int i = rangeStart; i < g_n; i++) { support = MathMin(support, g_l[i]); resistance = MathMax(resistance, g_h[i]); }
   double rangeSize = resistance - support;
   double midPrice = g_c[g_n - 1];
   double rangePct = rangeSize / midPrice;
   if(rangePct < WY_MIN_RANGE_PCT || rangePct > WY_MAX_RANGE_PCT) return;

   double touchBand = rangeSize * 0.20;
   double topBand = resistance - touchBand, botBand = support + touchBand;
   int topTouches = 0, botTouches = 0;
   for(int i = rangeStart; i < g_n; i++) { if(g_h[i] >= topBand) topTouches++; if(g_l[i] <= botBand) botTouches++; }
   if(topTouches < WY_MIN_RANGE_TOUCHES || botTouches < WY_MIN_RANGE_TOUCHES) return;

   int trendStart = MathMax(0, rangeStart - WY_TREND_BARS);
   if(rangeStart - trendStart < 4) return;
   double trendFirstClose = g_c[trendStart], trendLastClose = g_c[rangeStart - 1];
   double trendMove = trendLastClose - trendFirstClose;
   double trendPct = MathAbs(trendMove) / trendFirstClose;
   if(trendPct < 0.003) return;

   string phase = (trendMove < 0) ? "ACCUMULATION" : "DISTRIBUTION";

   // Spring / Upthrust (recentBars window) + volume average
   int scanStart = MathMax(rangeStart, g_n - WY_RECENT_BARS);
   double avgVol = 0; int cnt = 0;
   for(int i = rangeStart; i < g_n; i++) { avgVol += g_v[i]; cnt++; }
   if(cnt > 0) avgVol /= cnt;

   for(int i = scanStart; i < g_n; i++) {
      if(g_l[i] < support && g_l[i] >= support - WY_SPRING_MARGIN && g_c[i] > support && g_v[i] > avgVol) spring = true;
      if(g_h[i] > resistance && g_h[i] <= resistance + WY_UPTHRUST_MARGIN && g_c[i] < resistance && g_v[i] > avgVol) upthrust = true;
   }

   double upVol = 0, downVol = 0;
   for(int i = rangeStart; i < g_n; i++) { if(IsBull(i)) upVol += g_v[i]; else downVol += g_v[i]; }
   double totalVol = upVol + downVol;
   bool volumeConfirmed = false;
   if(totalVol > 0) {
      if(phase == "ACCUMULATION") volumeConfirmed = (upVol / totalVol) > 0.55;
      else volumeConfirmed = (downVol / totalVol) > 0.55;
   }

   double scoreRaw = 0.30;
   if(phase == "ACCUMULATION") { signal = "BUY"; if(spring) scoreRaw += 0.40; if(volumeConfirmed) scoreRaw += 0.30; }
   else { signal = "SELL"; if(upthrust) scoreRaw += 0.40; if(volumeConfirmed) scoreRaw += 0.30; }

   bool contradiction = (phase == "ACCUMULATION" && upthrust && !spring) || (phase == "DISTRIBUTION" && spring && !upthrust);
   if(contradiction) { signal = "NEUTRAL"; score = 0; return; }

   score = MathMin(1.0, scoreRaw);
}

//===================================================================
// PRICE ACTION — ports priceActionEngine.ts analyzePriceAction (CFG_M5)
//===================================================================
double CalcAtrPA() {
   int period = PA_ATR_PERIOD;
   int start = g_n - period - 1; if(start < 1) start = 1;
   double atr = 0; int cnt = 0;
   for(int i = start; i < g_n; i++) {
      double tr = MathMax(Rng(i), MathMax(MathAbs(g_h[i] - g_c[i-1]), MathAbs(g_l[i] - g_c[i-1])));
      atr += tr; cnt++;
   }
   return cnt > 0 ? atr / cnt : 0;
}

void AnalyzePriceAction(string &paSignal, double &paScore,
                         bool &bullEngulf, bool &bearEngulf, bool &bullPin, bool &bearPin,
                         bool &strongBull, bool &strongBear,
                         bool &nearDemand, bool &nearSupply, bool &nearSupport, bool &nearResistance,
                         bool &validBullBO, bool &validBearBO, bool &fakeBullBO, bool &fakeBearBO,
                         double &supportLevel, double &resistanceLevel) {
   paSignal = "NEUTRAL"; paScore = 0;
   bullEngulf = bearEngulf = bullPin = bearPin = strongBull = strongBear = false;
   nearDemand = nearSupply = nearSupport = nearResistance = false;
   validBullBO = validBearBO = fakeBullBO = fakeBearBO = false;
   supportLevel = 0; resistanceLevel = 0;

   if(g_n < PA_LEVEL_LOOKBACK + PA_ATR_PERIOD + 5) return;
   double atr = CalcAtrPA();
   if(atr <= 0) return;

   int n = g_n;
   int c0 = n - 1, c1 = n - 2;

   // Patterns
   double c0Body = Body(c0), c1Body = Body(c1);
   bullEngulf = IsBull(c0) && IsBear(c1) && g_o[c0] <= g_c[c1] && g_c[c0] >= g_o[c1] && c0Body >= c1Body * PA_ENGULF_BODY_RATIO;
   bearEngulf = IsBear(c0) && IsBull(c1) && g_o[c0] >= g_c[c1] && g_c[c0] <= g_o[c1] && c0Body >= c1Body * PA_ENGULF_BODY_RATIO;

   double r0 = Rng(c0);
   double minSize = atr * 0.25;
   bullPin = r0 >= minSize && BodyRatio(c0) <= PA_PINBAR_BODY_MAX_RATIO &&
             LowerWick(c0) >= Body(c0) * PA_PINBAR_WICK_RATIO && UpperWick(c0) <= LowerWick(c0) * 0.4;
   bearPin = r0 >= minSize && BodyRatio(c0) <= PA_PINBAR_BODY_MAX_RATIO &&
             UpperWick(c0) >= Body(c0) * PA_PINBAR_WICK_RATIO && LowerWick(c0) <= UpperWick(c0) * 0.4;

   double topOfRange = g_l[c0] + r0 * 0.80, bottomOfRange = g_l[c0] + r0 * 0.20;
   strongBull = IsBull(c0) && BodyRatio(c0) >= PA_STRONG_BODY_RATIO && Body(c0) >= atr * PA_STRONG_BODY_ATR_MULT && g_c[c0] >= topOfRange;
   strongBear = IsBear(c0) && BodyRatio(c0) >= PA_STRONG_BODY_RATIO && Body(c0) >= atr * PA_STRONG_BODY_ATR_MULT && g_c[c0] <= bottomOfRange;

   // S/R levels (swing highs/lows within lookback, clustered by tolerance)
   int lbStart = MathMax(0, n - PA_LEVEL_LOOKBACK);
   double resLevels[50]; int resCount = 0;
   double supLevels[50]; int supCount = 0;
   double rawHighs[50]; int rhCount = 0;
   double rawLows[50];  int rlCount = 0;
   for(int i = lbStart + 2; i < n - 2; i++) {
      if(g_h[i] > g_h[i-1] && g_h[i] > g_h[i-2] && g_h[i] > g_h[i+1] && g_h[i] > g_h[i+2] && rhCount < 50) rawHighs[rhCount++] = g_h[i];
      if(g_l[i] < g_l[i-1] && g_l[i] < g_l[i-2] && g_l[i] < g_l[i+1] && g_l[i] < g_l[i+2] && rlCount < 50) rawLows[rlCount++] = g_l[i];
   }
   ClusterLevels(rawHighs, rhCount, PA_LEVEL_TOLERANCE, PA_MIN_LEVEL_TOUCHES, resLevels, resCount);
   ClusterLevels(rawLows, rlCount, PA_LEVEL_TOLERANCE, PA_MIN_LEVEL_TOUCHES, supLevels, supCount);

   // Supply/demand zones (base + strong impulse)
   double demTop[10], demBot[10]; int demCount = 0;
   double supTop[10], supBot[10]; int supZCount = 0;
   for(int i = lbStart + 3; i < n - 1; i++) {
      double baseHigh = -1e9, baseLow = 1e9;
      for(int k = i - 3; k < i; k++) { baseHigh = MathMax(baseHigh, g_h[k]); baseLow = MathMin(baseLow, g_l[k]); }
      if(baseHigh - baseLow > atr * 1.5) continue;
      double impBody = Body(i), impRange = Rng(i);
      if(impRange <= 0) continue;
      bool strongImpulse = (impBody / impRange) >= PA_STRONG_BODY_RATIO && impBody >= atr * 0.5;
      if(!strongImpulse) continue;
      if(IsBull(i) && demCount < 10) { demTop[demCount] = baseHigh; demBot[demCount] = baseLow; demCount++; }
      else if(IsBear(i) && supZCount < 10) { supTop[supZCount] = baseHigh; supBot[supZCount] = baseLow; supZCount++; }
   }

   double currentPrice = g_c[n - 1];
   double tol = PA_LEVEL_TOLERANCE;
   for(int i = 0; i < supCount; i++) if(MathAbs(currentPrice - supLevels[i]) <= tol) { nearSupport = true; supportLevel = supLevels[i]; }
   for(int i = 0; i < resCount; i++) if(MathAbs(currentPrice - resLevels[i]) <= tol) { nearResistance = true; resistanceLevel = resLevels[i]; }
   for(int i = 0; i < demCount; i++) if(currentPrice >= demBot[i] - tol && currentPrice <= demTop[i] + tol) nearDemand = true;
   for(int i = 0; i < supZCount; i++) if(currentPrice >= supBot[i] - tol && currentPrice <= supTop[i] + tol) nearSupply = true;

   // Nearest levels for Capital Manager even when not "near" — smallest distance beyond price
   if(!nearResistance) { double best = 0; for(int i = 0; i < resCount; i++) if(resLevels[i] > currentPrice && (best == 0 || resLevels[i] < best)) best = resLevels[i]; resistanceLevel = best; }
   if(!nearSupport) { double best = 0; for(int i = 0; i < supCount; i++) if(supLevels[i] < currentPrice && (best == 0 || supLevels[i] > best)) best = supLevels[i]; supportLevel = best; }

   // Breakout / fake breakout
   int fb = MathMax(0, n - PA_FAKE_RETRACE_BARS - 1);
   for(int i = 0; i < resCount; i++) {
      double level = resLevels[i];
      if(currentPrice > level && Body(c0) >= PA_BREAKOUT_MIN_BODY && BodyRatio(c0) >= PA_BREAKOUT_BODY_RATIO && IsBull(c0)) validBullBO = true;
      for(int j = fb; j < n - 1; j++) if(g_c[j] > level && currentPrice < level) fakeBullBO = true;
   }
   for(int i = 0; i < supCount; i++) {
      double level = supLevels[i];
      if(currentPrice < level && Body(c0) >= PA_BREAKOUT_MIN_BODY && BodyRatio(c0) >= PA_BREAKOUT_BODY_RATIO && IsBear(c0)) validBearBO = true;
      for(int j = fb; j < n - 1; j++) if(g_c[j] < level && currentPrice > level) fakeBearBO = true;
   }

   // Pullback (not separately returned to caller — folded into composite score below)
   int trendLook = MathMin(10, n - 1);
   double priorClose = g_c[n - 1 - trendLook];
   bool trendUp = currentPrice > priorClose * 1.002;
   bool trendDown = currentPrice < priorClose * 0.998;
   double pullZone = currentPrice * PA_PULLBACK_ZONE_PCT;
   bool bullishPullback = false, bearishPullback = false;
   if(trendUp) {
      bool nearSup = false; for(int i = 0; i < supCount; i++) if(MathAbs(currentPrice - supLevels[i]) <= pullZone) nearSup = true;
      bool nearDem = false; for(int i = 0; i < demCount; i++) if(currentPrice >= demBot[i] - pullZone && currentPrice <= demTop[i] + pullZone) nearDem = true;
      if(nearSup || nearDem) bullishPullback = true;
   }
   if(trendDown) {
      bool nearRes = false; for(int i = 0; i < resCount; i++) if(MathAbs(currentPrice - resLevels[i]) <= pullZone) nearRes = true;
      bool nearSup2 = false; for(int i = 0; i < supZCount; i++) if(currentPrice >= supBot[i] - pullZone && currentPrice <= supTop[i] + pullZone) nearSup2 = true;
      if(nearRes || nearSup2) bearishPullback = true;
   }

   // Composite PA signal — computePaSignal weights (priceActionEngine.ts)
   double buyScore = 0, sellScore = 0;
   if(bullEngulf) buyScore += 1.5;
   if(bearEngulf) sellScore += 1.5;
   if(bullPin) buyScore += (nearSupport || nearDemand) ? 1.5 : 0.8;
   if(bearPin) sellScore += (nearResistance || nearSupply) ? 1.5 : 0.8;
   if(strongBull) buyScore += 1.0;
   if(strongBear) sellScore += 1.0;
   if(validBullBO) buyScore += 1.0;
   if(validBearBO) sellScore += 1.0;
   if(bullishPullback) buyScore += 0.8;
   if(bearishPullback) sellScore += 0.8;
   if(nearDemand || nearSupport) buyScore += 0.5;
   if(nearSupply || nearResistance) sellScore += 0.5;
   if(fakeBullBO) buyScore -= 1.5;
   if(fakeBearBO) sellScore -= 1.5;
   buyScore = MathMax(0, buyScore); sellScore = MathMax(0, sellScore);

   double maxPossible = 5.3;
   double dominant = MathMax(buyScore, sellScore);
   double score = NormalizeDouble(dominant / maxPossible, 2);
   if(buyScore > sellScore && score >= 0.30) paSignal = "BUY";
   if(sellScore > buyScore && score >= 0.30) paSignal = "SELL";
   paScore = MathMin(1.0, score);
}

void ClusterLevels(double &prices[], int count, double tol, int minTouches, double &outLevels[], int &outCount) {
   outCount = 0;
   bool used[50]; ArrayInitialize(used, 0);
   for(int i = 0; i < count; i++) {
      if(used[i]) continue;
      double sum = prices[i]; int grp = 1;
      for(int j = i + 1; j < count; j++) {
         if(!used[j] && MathAbs(prices[j] - prices[i]) <= tol) { sum += prices[j]; grp++; used[j] = true; }
      }
      used[i] = true;
      if(grp >= minTouches && outCount < 50) outLevels[outCount++] = sum / grp;
   }
}

//===================================================================
// TREND ENGINE — ports trendEngine.ts analyzeTrend (EMA50/100/200)
//===================================================================
void AnalyzeTrend(string &trend, string &strength) {
   trend = "NEUTRAL"; strength = "WEAK";
   if(g_n < 210) return; // matches trendEngine.ts's n<210 guard

   double ema50  = iMA(Symbol(), PERIOD_M5, 50,  0, MODE_EMA, PRICE_CLOSE, 1);
   double ema100 = iMA(Symbol(), PERIOD_M5, 100, 0, MODE_EMA, PRICE_CLOSE, 1);
   double ema200 = iMA(Symbol(), PERIOD_M5, 200, 0, MODE_EMA, PRICE_CLOSE, 1);
   double price  = g_c[g_n - 1];

   bool bullish5010 = price > ema50 && ema50 > ema100;
   bool bearish5010 = price < ema50 && ema50 < ema100;
   if(bullish5010) trend = "BULLISH";
   else if(bearish5010) trend = "BEARISH";

   if(trend == "BULLISH") strength = (ema100 > ema200) ? "STRONG" : "MODERATE";
   else if(trend == "BEARISH") strength = (ema100 < ema200) ? "STRONG" : "MODERATE";
}

//===================================================================
// CANDIDATE DIRECTION — CHoCH > BOS > finalTrend (v4.0)
// Replaces the old ComputeSmcSignal direction logic.
//===================================================================
string CalcSmcCandidateDir() {
   if(g_chochCount > 0) return g_choch[g_chochCount-1].dir; // strongest: structural reversal
   if(g_bosCount   > 0) return g_bos[g_bosCount-1].dir;     // secondary: continuation
   if(g_finalTrend == "BULLISH") return "BUY";
   if(g_finalTrend == "BEARISH") return "SELL";
   return "NEUTRAL";
}

//===================================================================
// QUALITY FILTER HELPERS — session / range / late-entry
//===================================================================
string SessionQuality() {
   // Use TimeGMT() so session windows match UTC hours in qualityFilter.ts.
   // TimeCurrent() is broker server time and would shift windows by the UTC offset.
   int hour = TimeHour(TimeGMT());
   if(hour >= 0  && hour < 3)  return "MODERATE"; // Asian early / Tokyo fix
   if(hour >= 6  && hour < 12) return "PRIME";    // London open
   if(hour >= 12 && hour < 16) return "PRIME";    // NY/London overlap
   if(hour >= 16 && hour < 17) return "MODERATE"; // NY afternoon
   return "BLOCKED";
}

bool IsVolatilityCompressed() {
   int lookback = 20;
   if(g_n < lookback + 2) return false;
   double currentATR = MathMax(Rng(g_n-1), MathMax(MathAbs(g_h[g_n-1]-g_c[g_n-2]), MathAbs(g_l[g_n-1]-g_c[g_n-2])));
   double sum = 0;
   for(int i = g_n - lookback - 1; i < g_n - 1; i++) {
      sum += MathMax(Rng(i), MathMax(MathAbs(g_h[i]-g_c[i-1]), MathAbs(g_l[i]-g_c[i-1])));
   }
   double meanATR = sum / lookback;
   return meanATR > 0 && currentATR < meanATR * 0.65;
}

bool IsSevereRange(double adx) {
   if(adx >= 22) return false;
   if(!IsVolatilityCompressed()) return false;
   double highest = -1e9, lowest = 1e9;
   for(int i = g_n - 15; i < g_n; i++) { highest = MathMax(highest, g_h[i]); lowest = MathMin(lowest, g_l[i]); }
   double recentRange = highest - lowest;
   double sum = 0;
   for(int i = g_n - 20; i < g_n; i++) sum += MathMax(Rng(i), MathMax(MathAbs(g_h[i]-g_c[i-1]), MathAbs(g_l[i]-g_c[i-1])));
   double meanATR = sum / 20;
   return recentRange < meanATR * 2.5;
}

double CalcEMA50Closes() {
   int period = 50;
   if(g_n < period) return g_c[g_n - 1];
   double k = 2.0 / (period + 1);
   double ema = 0;
   for(int i = 0; i < period; i++) ema += g_c[i];
   ema /= period;
   for(int i = period; i < g_n; i++) ema = g_c[i] * k + ema * (1 - k);
   return ema;
}

bool IsLateEntry(string smcSignal, int lastBosBarIndex) {
   if(smcSignal == "NEUTRAL") return false;
   int n = g_n;
   double price = g_c[n - 1];
   double atr = MathMax(Rng(n-1), MathMax(MathAbs(g_h[n-1]-g_c[n-2]), MathAbs(g_l[n-1]-g_c[n-2])));
   double ema50 = CalcEMA50Closes();
   if(MathAbs(price - ema50) > QF_LATE_EXTENSION_MULT * atr) return true;

   if(n >= QF_MOMENTUM_BARS + 1) {
      bool allBull = true, allBear = true;
      double bodies[10];
      for(int i = 0; i < QF_MOMENTUM_BARS; i++) {
         int idx = n - QF_MOMENTUM_BARS + i;
         if(!IsBull(idx)) allBull = false;
         if(!IsBear(idx)) allBear = false;
         bodies[i] = Body(idx);
      }
      if(allBull || allBear) {
         bool shrinking = true;
         for(int i = 1; i < QF_MOMENTUM_BARS; i++) if(bodies[i] > bodies[i-1]) shrinking = false;
         if(shrinking) return true;
      }
   }

   if(lastBosBarIndex >= 0) {
      int barAge = (n - 1) - lastBosBarIndex;
      if(barAge > QF_STALE_BAR_COUNT) return true;
   }
   return false;
}

//===================================================================
// ATR MEAN — 20-bar average True Range (helper for regime detector)
//===================================================================
double CalcAtrMean(int bars) {
   if(g_n < bars + 2) return 0;
   double sum = 0;
   for(int i = g_n - bars - 1; i < g_n - 1; i++) {
      if(i < 1) continue;
      sum += MathMax(Rng(i), MathMax(MathAbs(g_h[i]-g_c[i-1]), MathAbs(g_l[i]-g_c[i-1])));
   }
   return sum / bars;
}

//===================================================================
// MARKET REGIME DETECTOR — ports marketRegimeDetector.ts (v4.0)
// Sets globals: g_regime, g_minConf, g_minRR, g_allowLong, g_allowShort
//===================================================================
void DetectMarketRegime(double atr, double atrMean, double adx,
                         string trendDir, string trendStrength, string wySignal) {
   double atrRatio = (atrMean > 0) ? atr / atrMean : 1.0;

   // 1. HIGH VOLATILITY — ATR spike
   if(atrRatio > CONF_ATR_HIGH_VOL) {
      g_regime = "HIGH_VOLATILITY"; g_minConf = 93; g_minRR = 2.0;
      g_allowLong = true; g_allowShort = true; return;
   }
   // 2. LOW VOLATILITY — squeeze / dead zone
   if(atrRatio < CONF_ATR_LOW_VOL && adx < 20) {
      g_regime = "LOW_VOLATILITY"; g_minConf = 96; g_minRR = 2.5;
      g_allowLong = true; g_allowShort = true; return;
   }
   // 3. STRONG TREND — ADX>=30 + full EMA stack
   if(adx >= CONF_ADX_STRONG && trendStrength == "STRONG") {
      if(trendDir == "BULLISH") {
         g_regime = "STRONG_TREND_BULL"; g_minConf = 88; g_minRR = 1.5;
         g_allowLong = true; g_allowShort = false; return;
      }
      if(trendDir == "BEARISH") {
         g_regime = "STRONG_TREND_BEAR"; g_minConf = 88; g_minRR = 1.5;
         g_allowLong = false; g_allowShort = true; return;
      }
   }
   // 4. PULLBACK — short-term retracement within established trend
   if(g_n >= 7 && adx >= 20) {
      double now = g_c[g_n-1], prior = g_c[g_n-7];
      bool stBull = (now > prior * 1.0003);
      bool stBear = (now < prior * 0.9997);
      if(trendDir == "BULLISH" && stBear) {
         g_regime = "PULLBACK_BULL"; g_minConf = 90; g_minRR = 1.8;
         g_allowLong = true; g_allowShort = false; return;
      }
      if(trendDir == "BEARISH" && stBull) {
         g_regime = "PULLBACK_BEAR"; g_minConf = 90; g_minRR = 1.8;
         g_allowLong = false; g_allowShort = true; return;
      }
   }
   // 5. WEAK TREND — ADX 20-30, directional EMAs
   if(adx >= 20 && trendDir != "NEUTRAL") {
      if(trendDir == "BULLISH") {
         g_regime = "WEAK_TREND_BULL"; g_minConf = 92; g_minRR = 2.0;
         g_allowLong = true; g_allowShort = false; return;
      }
      g_regime = "WEAK_TREND_BEAR"; g_minConf = 92; g_minRR = 2.0;
      g_allowLong = false; g_allowShort = true; return;
   }
   // 6. WYCKOFF PHASES
   if(wySignal == "BUY") {
      g_regime = "ACCUMULATION"; g_minConf = 91; g_minRR = 2.0;
      g_allowLong = true; g_allowShort = false; return;
   }
   if(wySignal == "SELL") {
      g_regime = "DISTRIBUTION"; g_minConf = 91; g_minRR = 2.0;
      g_allowLong = false; g_allowShort = true; return;
   }
   // 7. RANGE (default)
   g_regime = "RANGE"; g_minConf = 96; g_minRR = 2.5;
   g_allowLong = true; g_allowShort = true;
}

//===================================================================
// CONFIDENCE SCORE ENGINE — ports confidenceEngine.ts calcConfidence (v4.0)
// Returns 0–100 confidence. Component scores are returned via out-params.
// Score bands: SMC 0-35 | Trend 0-20 | PA 0-20 | Wyckoff 0-15 | Liq 0-5 | Vol 0-5
//===================================================================
double CalcConfidenceScore(string candidate,
                            string wySignal, double wyScore, bool wySpring, bool wyUpthrust, bool wyVolConf,
                            string paSignal, double paScore,
                            bool paBullEngulf, bool paBearEngulf, bool paBullPin, bool paBearPin,
                            bool paStrongBull, bool paStrongBear,
                            bool paFakeBull, bool paFakeBear, bool paValidBullBO, bool paValidBearBO,
                            string emaTrend, string emaStrength,
                            string sessionQuality, double atrRatio, double adx,
                            bool hasSweep, bool hasEqLvl,
                            double &outSmc, double &outTrend, double &outPA,
                            double &outWyk, double &outLiq, double &outVol) {
   outSmc = 0; outTrend = 0; outPA = 0; outWyk = 0; outLiq = 0; outVol = 0;

   double cp = g_c[g_n - 1];

   // ── SMC Score (0–35) ──────────────────────────────────────────────
   // Structural trend alignment — 4 pts
   if(g_finalTrend == (candidate == "BUY" ? "BULLISH" : "BEARISH")) outSmc += 4.0;

   // BOS count — 5 or 7 pts
   int alignedBos = 0;
   for(int b = 0; b < g_bosCount; b++) if(g_bos[b].dir == candidate) alignedBos++;
   if(alignedBos >= 2) outSmc += 7.0; else if(alignedBos == 1) outSmc += 5.0;

   // CHoCH — strongest event, 8 pts
   if(g_chochCount > 0 && g_choch[g_chochCount-1].dir == candidate) outSmc += 8.0;

   // Order Blocks — dynamic quality scaling, up to 8 pts
   double obPts = 0; int obHits = 0;
   for(int i = 0; i < g_obCount && obHits < 2; i++) {
      bool typeMatch = (g_ob[i].typ == "BULLISH" && candidate == "BUY") ||
                       (g_ob[i].typ == "BEARISH" && candidate == "SELL");
      if(!typeMatch) continue;
      bool inZone   = (cp >= g_ob[i].low && cp <= g_ob[i].high);
      double edge   = (g_ob[i].typ == "BULLISH") ? g_ob[i].low : g_ob[i].high;
      bool nearZone = (MathAbs(cp - edge) <= SMC_NEAR_OB_THRESHOLD);
      if(!inZone && !nearZone) continue;
      // Dynamic: large-body OB scores higher
      int bIdx = g_ob[i].barIndex;
      double obBodyRatio = (Rng(bIdx) > 0) ? Body(bIdx) / Rng(bIdx) : 0;
      obPts += (obBodyRatio >= 0.50) ? 4.0 : 3.0;
      obHits++;
   }
   outSmc += MathMin(8.0, obPts);

   // FVGs — up to 4 pts
   int fvgHits = 0;
   for(int i = 0; i < g_fvgCount; i++) {
      bool typeMatch = (g_fvg[i].typ == "BULLISH" && candidate == "BUY") ||
                       (g_fvg[i].typ == "BEARISH" && candidate == "SELL");
      bool nearFvg = (cp >= g_fvg[i].bottom - SMC_NEAR_FVG_THRESHOLD &&
                      cp <= g_fvg[i].top    + SMC_NEAR_FVG_THRESHOLD);
      if(typeMatch && nearFvg) fvgHits++;
   }
   if(fvgHits >= 2) outSmc += 4.0; else if(fvgHits == 1) outSmc += 2.0;

   // Sweep — 4 pts
   if(hasSweep) outSmc += 4.0;
   outSmc = MathMin(35.0, outSmc);

   // ── Trend Score (0–20) ────────────────────────────────────────────
   string trendForDir = (candidate == "BUY") ? "BULLISH" : "BEARISH";
   if(emaTrend == trendForDir)       outTrend = (emaStrength == "STRONG") ? 20.0 : 14.0;
   else if(emaTrend == "NEUTRAL")    outTrend = 7.0;
   // Counter-trend = 0 (blocked upstream by hard EMA gate)

   // ── PA Score (0–20) ───────────────────────────────────────────────
   if(paSignal == candidate) {
      outPA = paScore * 13.0;
      if(candidate == "BUY") {
         if(paBullEngulf)      outPA += 4.0;
         else if(paBullPin)    outPA += 3.0;
         else if(paStrongBull) outPA += 2.0;
         if(paValidBullBO)     outPA += 2.0;
         if(paFakeBull)        outPA -= 6.0;
      } else {
         if(paBearEngulf)      outPA += 4.0;
         else if(paBearPin)    outPA += 3.0;
         else if(paStrongBear) outPA += 2.0;
         if(paValidBearBO)     outPA += 2.0;
         if(paFakeBear)        outPA -= 6.0;
      }
   }
   outPA = MathMax(0.0, MathMin(20.0, outPA));

   // ── Wyckoff Score (0–15) ──────────────────────────────────────────
   if(wySignal == candidate) {
      outWyk = wyScore * 8.0;
      if(candidate == "BUY"  && wySpring)   outWyk += 4.0;
      if(candidate == "SELL" && wyUpthrust) outWyk += 4.0;
      if(wyVolConf)                          outWyk += 3.0;
   }
   outWyk = MathMin(15.0, outWyk);

   // ── Liquidity Score (0–5) ─────────────────────────────────────────
   if(hasSweep)  outLiq += 2.5;
   if(hasEqLvl)  outLiq += 1.5;
   if(hasSweep && alignedBos > 0) outLiq += 1.0; // sweep + BOS confluence
   outLiq = MathMin(5.0, outLiq);

   // ── Volatility / Session Score (0–5) ─────────────────────────────
   if(sessionQuality == "PRIME")         outVol += 2.5;
   else if(sessionQuality == "MODERATE") outVol += 1.0;
   if(adx >= 30)      outVol += 1.5;
   else if(adx >= 20) outVol += 0.75;
   if(atrRatio >= 0.8 && atrRatio <= 1.5) outVol += 1.0;
   else if(atrRatio > 1.5)                outVol += 0.5;
   outVol = MathMin(5.0, outVol);

   return NormalizeDouble(outSmc + outTrend + outPA + outWyk + outLiq + outVol, 1);
}

//===================================================================
// ENHANCED QUALITY FILTER — 10-category rejection gate (v4.0)
//===================================================================
bool EnhancedQualityFilter(string candidate, double confidence, double rrRatio,
                             string sessionQuality, double adx, string &blockReason) {
   blockReason = "";

   // ① Session gate
   if(sessionQuality == "BLOCKED") {
      blockReason = "Session: Dead zone (no XAUUSD liquidity)"; return false;
   }
   // ② No SMC structure at all
   if(g_bosCount == 0 && g_chochCount == 0) {
      blockReason = "No BOS or CHoCH detected"; return false;
   }
   // ③ Severe range (ADX + ATR compressed + tight band)
   if(IsSevereRange(adx)) {
      blockReason = StringFormat("Severe range: ADX=%.1f + ATR compressed", adx); return false;
   }
   // ④ Late entry (overextended from EMA50, exhausted momentum, or stale BOS)
   int lastBosIdx = (g_bosCount > 0) ? g_bos[g_bosCount-1].barIndex : -1;
   if(IsLateEntry(candidate, lastBosIdx)) {
      blockReason = "Late entry: overextended from EMA50 or stale BOS"; return false;
   }
   // ⑤ Low momentum (ADX < 15)
   if(adx < CONF_ADX_MIN) {
      blockReason = StringFormat("Low momentum: ADX=%.1f < %.0f", adx, CONF_ADX_MIN); return false;
   }
   // ⑥ Weak volume (signal bar < 40% of 20-bar average)
   {
      double avgVol = 0; int cnt = 0;
      for(int i = g_n - 21; i < g_n - 1; i++) { if(i >= 0) { avgVol += g_v[i]; cnt++; } }
      if(cnt > 0) avgVol /= cnt;
      if(avgVol > 0 && g_v[g_n-1] < avgVol * 0.40) {
         blockReason = "Weak volume: signal bar < 40% of 20-bar average"; return false;
      }
   }
   // ⑦ Direction not allowed in current regime
   if(candidate == "BUY"  && !g_allowLong)  { blockReason = "Regime " + g_regime + " blocks LONG";  return false; }
   if(candidate == "SELL" && !g_allowShort) { blockReason = "Regime " + g_regime + " blocks SHORT"; return false; }
   // ⑧ Hard confidence minimum (85%)
   if(confidence < CONF_HARD_MIN) {
      blockReason = StringFormat("Confidence %.1f%% < %.0f%% hard minimum", confidence, CONF_HARD_MIN); return false;
   }
   // ⑨ Marginal zone (85%–regime floor): only pass if R:R >= 2.0
   if(confidence < g_minConf) {
      if(rrRatio >= CONF_MARGINAL_MIN_RR) return true; // marginal pass
      blockReason = StringFormat("Marginal conf %.1f%% needs R:R>=%.1f (got %.2f, regime=%s)",
                                  confidence, CONF_MARGINAL_MIN_RR, rrRatio, g_regime);
      return false;
   }
   // ⑩ R:R gate (regime-specific minimum)
   if(rrRatio < g_minRR) {
      blockReason = StringFormat("R:R %.2f < %.1f min for %s", rrRatio, g_minRR, g_regime); return false;
   }

   return true;
}

//===================================================================
// DECISION LOGGER — structured per-trade decision log (v4.0)
//===================================================================
void LogDecision(string dir, double confidence, string regime,
                  double smcPts, double trendPts, double paPts,
                  double wykPts, double liqPts, double volPts,
                  double rrRatio, bool allowed, string blockReason) {
   string bar = "============================================================";
   if(allowed) {
      Print(bar);
      Print(">>> TRADE: ", dir,
            " | Confidence: ", DoubleToString(confidence, 1), "%",
            " | R:R: ",        DoubleToString(rrRatio, 2),
            " | Regime: ",     regime);
      Print("    SMC=",     DoubleToString(smcPts,  1), "/35",
            "  Trend=",    DoubleToString(trendPts, 1), "/20",
            "  PA=",       DoubleToString(paPts,    1), "/20");
      Print("    Wyckoff=", DoubleToString(wykPts,  1), "/15",
            "  Liq=",      DoubleToString(liqPts,   1), "/5",
            "  VolSes=",   DoubleToString(volPts,   1), "/5");
      string ev = "";
      if(g_chochCount > 0)  ev += "CHoCH ";
      if(g_bosCount   > 0)  ev += "BOS ";
      if(g_obCount    > 0)  ev += "OB ";
      if(g_fvgCount   > 0)  ev += "FVG ";
      if(g_sweepCount > 0)  ev += "Sweep ";
      if(ev == "")          ev  = "Structure";
      Print("    Evidence: ", ev);
      Print(bar);
   } else {
      Print(">>> SKIP: ", dir,
            " | Conf: ", DoubleToString(confidence, 1), "%",
            " | ", blockReason);
   }
}

//===================================================================
// CAPITAL MANAGER — ports capitalManager.ts calcTradeParameters
//===================================================================
void CalcTradeParameters(string direction, double entry, double atr,
                          bool haveOb, double obTop, double obBottom,
                          double swingHigh, double swingLow,
                          double resistanceLevel, double supportLevel,
                          double &sl, double &tp, double &trailDist, double &trailActivateAt,
                          double &beAt, double &beSL, double &lots, double &riskAmount) {
   double buffer = atr * CM_ATR_BUFFER_MULT;
   double minSL = atr * CM_MIN_SL_ATR_MULT;
   double maxSL = atr * CM_MAX_SL_ATR_MULT;

   double slDist;
   bool haveStruct = false; double structLevel = 0;

   if(direction == "BUY") {
      double best = -1;
      if(haveOb && obBottom < entry && obBottom > best) { best = obBottom; haveStruct = true; }
      if(swingLow > 0 && swingLow < entry && swingLow > best) { best = swingLow; haveStruct = true; }
      if(supportLevel > 0 && supportLevel < entry && supportLevel > best) { best = supportLevel; haveStruct = true; }
      structLevel = best;
   } else {
      double best = 1e12;
      if(haveOb && obTop > entry && obTop < best) { best = obTop; haveStruct = true; }
      if(swingHigh > 0 && swingHigh > entry && swingHigh < best) { best = swingHigh; haveStruct = true; }
      if(resistanceLevel > 0 && resistanceLevel > entry && resistanceLevel < best) { best = resistanceLevel; haveStruct = true; }
      structLevel = best;
   }

   if(haveStruct) slDist = MathAbs(entry - structLevel) + buffer;
   else slDist = atr * 1.5; // fallback, matches capitalManager.ts

   slDist = MathMax(minSL, MathMin(maxSL, slDist));
   sl = NormalizeDouble(direction == "BUY" ? entry - slDist : entry + slDist, Digits);

   // Dynamic TP
   double minTPDist = slDist * CM_MIN_REWARD_RISK;
   double maxTPDist = atr * CM_MAX_TP_ATR_MULT;
   double tpDist; bool haveTpLevel = false; double tpLevel = 0;
   if(direction == "BUY") {
      double best = 1e12;
      if(resistanceLevel > entry + minTPDist && resistanceLevel < best) { best = resistanceLevel; haveTpLevel = true; }
      if(swingHigh > entry + minTPDist && swingHigh < best) { best = swingHigh; haveTpLevel = true; }
      tpLevel = best;
   } else {
      double best = -1;
      if(supportLevel > 0 && supportLevel < entry - minTPDist && supportLevel > best) { best = supportLevel; haveTpLevel = true; }
      if(swingLow > 0 && swingLow < entry - minTPDist && swingLow > best) { best = swingLow; haveTpLevel = true; }
      tpLevel = best;
   }
   tpDist = haveTpLevel ? MathAbs(entry - tpLevel) : minTPDist;
   tpDist = MathMax(minTPDist, MathMin(maxTPDist, tpDist));
   tp = NormalizeDouble(direction == "BUY" ? entry + tpDist : entry - tpDist, Digits);

   // Trailing stop
   trailDist = NormalizeDouble(atr * CM_TRAIL_ATR_MULT, Digits);
   double activationDist = slDist * CM_TRAIL_ACTIVATION;
   trailActivateAt = NormalizeDouble(direction == "BUY" ? entry + activationDist : entry - activationDist, Digits);

   // Break-even
   double beTriggerDist = slDist * CM_BE_ACTIVATION;
   double beBuffer = atr * CM_BE_BUFFER_MULT;
   beAt = NormalizeDouble(direction == "BUY" ? entry + beTriggerDist : entry - beTriggerDist, Digits);
   beSL = NormalizeDouble(direction == "BUY" ? entry + beBuffer : entry - beBuffer, Digits);

   // Position sizing — 1% risk, $100/lot per $1 move (XAUUSD convention)
   double balance = AccountBalance();
   double riskPct = Risk_Per_Trade;
   double riskAmt = balance * riskPct / 100.0;
   double rawLot = riskAmt / (slDist * CM_LOT_DOLLAR_PER_UNIT);
   lots = MathMax(CM_MIN_LOT, MathMin(CM_MAX_LOT, rawLot));

   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
   if(lotStep > 0) lots = MathFloor(lots / lotStep) * lotStep;
   lots = MathMax(minLot, MathMin(maxLot, lots));
   riskAmount = NormalizeDouble(lots * slDist * CM_LOT_DOLLAR_PER_UNIT, 2);
}

//===================================================================
// RISK GUARD, ORDER EXECUTION & MANAGEMENT (unchanged mechanics)
//===================================================================
bool IsRiskAllowed() {
   double balance = AccountBalance();
   double equity  = AccountEquity();
   double dailyLoss = (g_DailyStartBalance - equity) / g_DailyStartBalance * 100;
   if(dailyLoss >= Max_Daily_Loss) { Print("Daily loss limit reached: ", DoubleToStr(dailyLoss, 2), "%"); return false; }
   double drawdown = (balance - equity) / balance * 100;
   if(drawdown >= Max_Drawdown) { Print("Max drawdown reached: ", DoubleToStr(drawdown, 2), "%"); return false; }
   return true;
}

void OpenTrade(int type, double lots, double price, double sl, double tp) {
   int ticket = OrderSend(Symbol(), type, lots, price, 3, sl, tp, EA_Comment, Magic_Number, 0, type == OP_BUY ? clrBlue : clrRed);
   if(ticket < 0) Print("OrderSend failed: ", GetLastError());
   else Print("Trade opened: ticket=", ticket, " type=", (type == OP_BUY ? "BUY" : "SELL"), " lots=", lots, " SL=", sl, " TP=", tp);
}

int CountOpenTrades() {
   int count = 0;
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
         if(OrderSymbol() == Symbol() && OrderMagicNumber() == Magic_Number) count++;
      }
   }
   return count;
}

// Trailing stop + break-even, per Capital Manager's trailingStopDistance/
// trailingActivationAt/breakEvenAt/breakEvenSL (recomputed from current ATR
// and the order's own entry, since MQL4 orders don't persist custom fields).
void ManageOpenTrades() {
   double atr = iATR(Symbol(), PERIOD_M5, ATR_Period, 1);
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if(OrderSymbol() != Symbol() || OrderMagicNumber() != Magic_Number) continue;

      double entry = OrderOpenPrice();
      double origSl = OrderStopLoss();
      double slDist = MathAbs(entry - origSl);
      if(slDist <= 0) continue;

      double beBuffer = atr * CM_BE_BUFFER_MULT;
      double trailDist = atr * CM_TRAIL_ATR_MULT;

      if(OrderType() == OP_BUY) {
         double beAt = entry + slDist * CM_BE_ACTIVATION;
         double trailAt = entry + slDist * CM_TRAIL_ACTIVATION;
         if(Bid >= trailAt) {
            double newSl = NormalizeDouble(Bid - trailDist, Digits);
            if(newSl > OrderStopLoss()) OrderModify(OrderTicket(), entry, newSl, OrderTakeProfit(), 0, clrNone);
         } else if(Bid >= beAt && OrderStopLoss() < entry) {
            OrderModify(OrderTicket(), entry, NormalizeDouble(entry + beBuffer, Digits), OrderTakeProfit(), 0, clrNone);
         }
      } else if(OrderType() == OP_SELL) {
         double beAt = entry - slDist * CM_BE_ACTIVATION;
         double trailAt = entry - slDist * CM_TRAIL_ACTIVATION;
         if(Ask <= trailAt) {
            double newSl = NormalizeDouble(Ask + trailDist, Digits);
            if(newSl < OrderStopLoss() || OrderStopLoss() == 0) OrderModify(OrderTicket(), entry, newSl, OrderTakeProfit(), 0, clrNone);
         } else if(Ask <= beAt && (OrderStopLoss() > entry || OrderStopLoss() == 0)) {
            OrderModify(OrderTicket(), entry, NormalizeDouble(entry - beBuffer, Digits), OrderTakeProfit(), 0, clrNone);
         }
      }
   }
}

bool IsNewBar() {
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(Symbol(), PERIOD_M5, 0);
   if(currentBarTime != lastBarTime) { lastBarTime = currentBarTime; return true; }
   return false;
}
//+------------------------------------------------------------------+`;
}
